# Generated by Django 4.0.2 on 2024-01-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_and_save_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa instytucji')),
                ('description', models.TextField(verbose_name='Opis instytucji/organizacji/fundacji')),
                ('type', models.CharField(choices=[('Fundacja', 1), ('Organizacja pozarządowa', 2), ('Zbiórka lokalna', 3)], default='Fundacja', max_length=150, verbose_name='Typ organizacji')),
                ('categories', models.ManyToManyField(to='share_and_save_app.Category', verbose_name='Kategoria')),
            ],
        ),
    ]
