# Generated by Django 4.0.2 on 2024-01-15 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import share_and_save_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('share_and_save_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', share_and_save_app.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 15, 13, 48, 0, 689268, tzinfo=utc), verbose_name='Data odbioru'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(default='14:48:00', verbose_name='Godzina odbioru'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
