# Generated by Django 4.0.2 on 2024-01-10 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share_and_save_app', '0002_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Liczba worków')),
                ('address', models.CharField(max_length=150, verbose_name='Ulica i numer domu/mieszkania')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Number telefonu')),
                ('city', models.CharField(max_length=50, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateField(default=datetime.date(2024, 1, 10), verbose_name='Data odbioru')),
                ('pick_up_time', models.TimeField(default='14:59:19', verbose_name='Godzina odbioru')),
                ('pick_up_comment', models.TextField(verbose_name='Dodatkowe informacje')),
                ('categories', models.ManyToManyField(to='share_and_save_app.Category', verbose_name='Kategoria')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_and_save_app.institution', verbose_name='Instytucja')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
