# Generated by Django 4.0.2 on 2024-01-10 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('share_and_save_app', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 14, 0, 33, 565816, tzinfo=utc), verbose_name='Data odbioru'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(default='15:00:33', verbose_name='Godzina odbioru'),
        ),
    ]
